"""crear tablas iniciales

Revision ID: 5869798adfb4
Revises: 
Create Date: 2026-04-10 17:05:31.905285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5869798adfb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ciudades_nombre', 'ciudades', ['nombre'], unique=False)
    op.create_index('ix_metricas_etl_fecha', 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_index('idx_ciudad_fecha', 'registros_clima', ['ciudad_id', 'fecha_extraccion'], unique=False)
    op.create_index('ix_registros_clima_ciudad_id', 'registros_clima', ['ciudad_id'], unique=False)
    op.create_index('ix_registros_clima_fecha_extraccion', 'registros_clima', ['fecha_extraccion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registros_clima_fecha_extraccion', table_name='registros_clima')
    op.drop_index('ix_registros_clima_ciudad_id', table_name='registros_clima')
    op.drop_index('idx_ciudad_fecha', table_name='registros_clima')
    op.drop_index('ix_metricas_etl_fecha', table_name='metricas_etl')
    op.drop_index('ix_ciudades_nombre', table_name='ciudades')
    # ### end Alembic commands ###
