"""primera_migracion_indicadores_pib

Revision ID: 83f4fb4e9e9f
Revises: 09a26d9dd8c8
Create Date: 2026-04-13 16:40:49.192710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f4fb4e9e9f'
down_revision: Union[str, Sequence[str], None] = '09a26d9dd8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
